const PRIMARY_COLOR = '#FFFFFF';
const SECONDARY_COLOR = '#00CFF5';
const ACTIONS_COLOR = '#006FB5';
const TITLES_COLOR = '#434343';
const LABELS_COLOR = '#71717A';

export {
    PRIMARY_COLOR,
    SECONDARY_COLOR,
    ACTIONS_COLOR,
    TITLES_COLOR,
    LABELS_COLOR
}